### ISSUE TITLE
"Install" Button is not performing any actions

### ISSUE THREAD

**Issue by DontBotherYT** [domferr/Linux-PowerToys#1]
Upon loading into the GUI, I navigate into the "Fancy Zones" category and attempt to install using the button. 
But when clicking the "install" button, nothing happens. No dialogue or action occurs to visually prompt that the program is attempting to install the requested plugin. 

To provide context for what may be missing or if there's an error, I'd recommend just a small dialogue pop-up that references the missing functions or provides further instruction to repair the tool.

**Comment by domferr** [comment]
Which is your OS and desktop environment?

**Comment by DontBotherYT** [comment]
Linux Mint 21.2 x86_64, DE: Cinnamon 5.8.4

**Comment by domferr** [comment]
Unfortunately, the current version of Linux PowerToys is compatible with GNOME only since it installs gnome extensions.

I'm not an expert on Cinnamon, but it may be possible to install the [gnome extension](https://github.com/GnomeSnapExtensions/gSnap/tree/40-44) FancyZones needs, to see if it works or not. If that's the case, I could easily update Linux Power Toys to add the support to Cinnamon!
